fedibtc/fedimint-ui

- apps/guardian-ui/src/components/VerifyGuardians.tsx
- apps/guardian-ui/src/types.tsx
- apps/guardian-ui/src/utils/api.ts
The api returns `our_current_id` for `get_verify_config_hash`, so we use that. Since PeerId is part of ConsensusConfigGenParams too, we can determine which peer we are/are not.
> Use API for Peer Id

- apps/guardian-ui/src/GuardianContext.tsx
- apps/guardian-ui/src/components/ConnectGuardians.tsx
- apps/guardian-ui/src/types.tsx
Saves `our_current_id` from the API to GuardianContext. 
Then uses that to filter and display `api_url` from `peers`.
Previously, it was displaying the url from the ENV VAR `REACT_APP_FM_CONFIG_API` which may not always be the same.
> 1 connectguardianstsx displays wrong value

- mprocs.yml
Useful for when you need to clear the federation data and restart a setup.
> build: adds clear-federation-data to mprocs

- README.md
- mprocs.yml
Tried to use mprocs for dev and realized
1. I need `clear-federation-data` and `teardown-ui-federation` to be in the same process so I don't clear data without teardown
2. I need sudo to remove `fm_*` dirs
Refactored this definition and ended with this mprocs def.
Also runs a gateway-ui instance
> build: iterate mprocs definition

- mprocs.yml
Adds an option to retain data when stopping fedimintd servers.
Adds an options for logs from only a sinlge fedimintd instance for better organization/debugging.
> build: adds additional mprocs processes

- .github/workflows/gateway-ui.yml
- .github/workflows/guardian-ui.yml
- Dockerfile.gateway-ui
- Dockerfile.guardian-ui
- docker-compose.yml
- package.json
- scripts/replace-react-env.js
Built on top of #68, do not merge until that is merged
* Adds `scripts/replace-react-env.js` for replacing environment variables with environment variable values
* Dockerfile `yarn build` sets these to handlebars-style values of the env varname
* e.g. `REACT_APP_FM_GATEWAY_API="{{REACT_APP_FM_GATEWAY_API}}"`
* Dockerfile `CMD` runs this before `serve` to update with runtime env vars instead of doing full rebuild
* Only targets env vars with `REACT_APP_` prefix
* I made a node script instead of a shell script because I suck at bash, feel free to replace with a sed one-liner if you're a god
* Adds `yarn build:[app]` commands for building individual apps
* The dockerfiles use these instead of the full `yarn build` to only build the relevant app
> refactor: better docker build & run performance

- apps/gateway-ui/src/types.tsx
- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/components/ConnectGuardians.tsx
- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/setup/types.tsx
- apps/guardian-ui/src/types.tsx
- apps/guardian-ui/src/utils/api.ts
Adds admin apis for fetching client config and listing registered gateways.
- To fetch config, we need connection string
```ts
const [config, setConfig] = useState<ConfigResponse>();
api.config(connectionCode).then(setConfig).catch(console.error);
```
- To list gateways, we need config, from which we can determine the lightning module id
```ts
const [gateways, setGateways] = useState<object>(['foo']);
if (config) {
for (const [key, val] of Object.entries(config.client_config.modules)) {
if (val.kind === 'ln') {
api
.moduleApiCall<Gateway[]>(key, LightningModuleRpc.listGateways)
.then(setGateways)
.catch(console.error);
return;
}
}
}
```
> Config and List Gateways API

- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/setup/SetupContext.tsx
* Expose the api to the window as `window.fedimintApi` for debugging purposes
* Increase RPC timeout to 5 minutes to allow for longer dkg
> Misc. dev call fixes

- apps/gateway-ui/src/components/WithdrawTab.tsx
- apps/guardian-ui/src/setup/FederationSetup.tsx
- packages/utils/src/i18n.tsx
The fallback language should be `en-US`, instead of `en`. And other clean ups
> Fix fallback language

- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/components/VerifyGuardians.tsx
- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/types.tsx
- flake.lock
- flake.nix
https://github.com/fedimint/fedimint/pull/2807 adds `VerifiedConfigs` state to which all guardians should wait before proceeding to start consensus. This change progresses a guardian to this state, immediately they verify all peer configs, and starts watching other guardian servers for progress through the verification step.
- With the addition of https://github.com/fedimint/fedimint/pull/2808, Guardians can also safely reload the verify configs page to access and share their config code
fixes #14
> feat: wait for all guardians to verify configs before start consensus

- apps/guardian-ui/src/setup/FederationSetup.tsx
Just realized we lost the setup progress indicator as [part of the very large change](https://github.com/fedimint/ui/pull/24/commits/bdf68e2d76fc0eedd3a045f0e10520fe0ff70d05#diff-7678898746f2fa77f54469178ef028a4dda9a5c6543ebac6e3cd465dadd26640) introducing translations. We need more acute reviews, and #5 should help flag this kind of experience regressions
> fix: re-introduce setup progress indicator

- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/setup/types.tsx
- flake.lock
- flake.nix
This block of code handling the config gen params is very error-prone. Related to https://github.com/fedimint/ui/issues/12.
> fix: include default client bitcoin rpc config in params

- apps/guardian-ui/src/App.tsx
- apps/guardian-ui/src/AppContext.tsx
- apps/guardian-ui/src/setup/FederationSetup.tsx
- apps/guardian-ui/src/setup/SetupContext.tsx
- apps/guardian-ui/src/setup/types.tsx
Simplifies application state management in Setup and admin UIs with the results that:
- Setup UI has a perceived faster load since we establish socket connections earlier when booting the app.
- On boot, we always check latest server state to determine experience flow into Setup vs Admin UI
- Guardians can smoothly navigate back and forth, and reload the pages at every single step of setup UI
- On transition to Admin experience, we clear all setup-state persisted in local storage
fixes #34
> Improve guardian ui boot experience

- apps/guardian-ui/src/App.tsx
- apps/guardian-ui/src/AppContext.tsx
- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/components/Login.tsx
- apps/guardian-ui/src/components/SetupComplete.tsx
- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/languages/es.json
- apps/guardian-ui/src/setup/FederationSetup.tsx
- apps/guardian-ui/src/setup/SetupContext.tsx
- apps/guardian-ui/src/setup/types.tsx
- apps/guardian-ui/src/types.tsx
- flake.lock
- flake.nix
Secure app experiences by validating auth against FM servers
- https://github.com/fedimint/fedimint/pull/2820
- https://github.com/fedimint/fedimint/pull/2823
This change applies auth as a top-level experience at the app level. A user must first pass the auth challenge (where necessary) To get to setup or admin experiences.
> Guardian UI app-wide auth

- docker-compose.yml
Using `master` tag is error-prone because if you've already pulled it and an update is made to backend which the UI needs, docker won't re-download this new tag unless you manually run a command like `docker pull fedimintd` / `docker pull gatewayd`.
> feat: use git tags for fedimint docker images

- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/setup/types.tsx
- apps/guardian-ui/src/utils/api.ts
- docker-compose.yml
- flake.lock
- flake.nix
This allows the UI to run 3rd party modules. It doesn't expose their parameters in the UI so you can only run with default parameters. But it's a good step forward. I was able to test it with a 3rd party module and it worked.
@wbobeirne could use a little help with typing things.
Updated docker and nix fedimint hashes to include [this commit](https://github.com/fedimint/fedimint/pull/2848) which enables devimint to do DKG with 3rd party modules.
> Don't throw away 3rd party modules

- JUSTFILE
- apps/guardian-ui/src/components/VerifyGuardians.tsx
- adds a catch to skip showing verifyguardians if it's a 1/1 federation.
- adds a JUSTFILE for commands
> fix: no verifyGuardians page for solo + JUSTFILE

- apps/guardian-ui/src/setup/types.tsx
fixes #153 
should be `bitcoin` not `mainnet` because of these rust bitcoin types: https://docs.rs/bitcoin/latest/bitcoin/network/constants/enum.Network.html
I tested this by changing the HTML so that `<option value="bitcoin">` and submitted the form and it works
> fix: mainnet key should be `bitcoin`

- README.md
- docker-compose.yml
- flake.lock
- flake.nix
Use v0.1.0-rc3 git tag for docker and nix fedimint deps.
I can complete the setup using docker, but sometimes need to refresh the last page to get to the dashboard. Not sure what is causing that.
Also, the docker setup doesn't mine any blocks (this is one of many nice things that devimint automates for us) and so it seems like after DKG completes the federation just keeps producing tons of rounds of consensus trying to get a first bitcoin block.
> fix: update fedimint version to v0.1 branch

- apps/guardian-ui/src/components/VerifyGuardians.tsx
- apps/guardian-ui/src/languages/en.json
Closes #169.
* Runs `api.runConsensus` before continuing from the `VerifyGuardians` step if you're a solo federation
* Renders a spinner instead of the verify configs table while this is happening
* The header and description copy is still kinda wrong since there are no other guardians, but we can refine this later
https://github.com/fedimint/ui/assets/649992/fc40b642-e285-4dc7-8004-9c1cad30e7af
> fix(guardian-ui): run consensus in VerifyGuardians before continuing

- README.md
Relative `DEVIMINT_PATH` caused some things to fail, this updates the suggest using `realpath` to blow it up into an absolute path instead.
> docs: fix devimint path to be absolute

- docker-compose.yml
- flake.lock
- flake.nix
I've been using this locally for a while and run through setup quite a few times, no breaking changes.
Unblocks #174 to be ready to review & merge.
> chore: upgrade fedimint nix dependency and docker containers to 0.1.0 release

- apps/guardian-ui/src/AppContext.tsx
- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/setup/SetupContext.tsx
Closes #134
* Don't save password to `sessionStorage` if `save_password` RPC failed
* Run `testPassword` during initial load check instead of assuming it's valid, set `needsAuth` if it fails
* Initialize `SetupContext`'s `password` state with `api.getPassword()`
* Since this is set, we can simplify the logic for not re-submitting password during `submitConfiguration()`
1. Get to the setup configuration form as a Leader
2. Fill out the form with an invalid Bitcoin RPC URI and submit, confirm you get an error
3. Scroll up to the password input, confirm it has become read-only
4. Refresh the page, confirm the password input is filled in and read-only
6. Edit your `sessionStorage` in the developer tools and set the password to an invalid password and refresh, confirm you are asked to login
* …
> Fix password logic

- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/admin/FederationAdmin.tsx
- apps/guardian-ui/src/components/BitcoinNodeCard.tsx
- apps/guardian-ui/src/components/ConnectGuardians.tsx
- apps/guardian-ui/src/components/RoleSelector.tsx
- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/components/SetupProgress.tsx
- apps/guardian-ui/src/components/VerifyGuardians.tsx
- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/setup/FederationSetup.tsx
- apps/guardian-ui/src/setup/SetupContext.tsx
- apps/guardian-ui/src/types/api.ts
- apps/guardian-ui/src/types/app.ts
- apps/guardian-ui/src/types/index.ts
- apps/guardian-ui/src/types/setup.ts
- apps/guardian-ui/src/utils/api.ts
Built off of #168. Accomplishes the bitcoin node info part of #95.
Marking as draft until https://github.com/fedimint/fedimint/pull/3072 gets made into a new release candidate (v0.1.0-rc4).
* Hooks up the new `modules_config_json` rpc to an `api.modulesConfig()` method
* Hooks up `api.modulesConfig()` to the `<BitcoinNodeCard />` component
* Replaced the "Block height" key / value with "Network" since we do not yet have a way to get block height
* Refactors all `guardian-ui` types to live in a single `types/` directory due to how frequently types are shared
* Types can be separated into files, e.g. the old `types.ts` is split into `types/app.ts` and `types/api.ts`
* Moved `setup/types.ts` into `types/setup.ts`, updated imports
* There's likely more consolidation and cleanup that can be …
> Bitcoin node config + types refactor

- apps/gateway-ui/src/components/FederationCard.tsx
- apps/gateway-ui/src/languages/en.json
- apps/gateway-ui/src/types.tsx
Closes #167. Marked as draft until #193 is merged since that has the versions with the updated endpoint.
* Renders `federation.config.meta.federation_name` with fallback to default i18nified title
* Adds types for new `config` property on `Federation`
* See #201 for future refactor
> fix(gateway-ui): use real federation name instead of hard-coded name

- apps/guardian-ui/src/components/RunDKG.tsx
> fix: DKG status error message renders

- docker-compose.yml
- flake.lock
- flake.nix
This PR updates the nix and docker fedimint dependencies to the merge commit for [AlephBFT support ](https://github.com/fedimint/fedimint/pull/3313)
I successfully completed 3/4 local federation setups using both docker (`just mprocs`) and nix `(yarn nix-guardian`)
> Update fedimint to version with AlephBFT

- apps/gateway-ui/src/GatewayApi.ts
- apps/gateway-ui/src/components/BalanceCard.tsx
- apps/gateway-ui/src/components/FederationCard.tsx
- apps/gateway-ui/src/components/WithdrawCard.tsx
- removes quotations around deposit address
- shows gateway balance as sats (instead of msats)
- shows the correct balance available for withdrawal
- fixes number input in withdraw card
- enables 'withdraw all button' though this should not be used?
> gateway ui fixes

- README.md
[Click here to view the rendered version of the README](https://github.com/fedimint/ui/blob/wo/readme-versions/README.md)
1. Moved screenshots to top
2. Added information about how version numbers work between ui and fedimint
3. Moved instructions for running the release above development instructions
4. Removed some of the v0.1.0-specific text from running a release
> docs: add information about versioning, reorganize running release

- .dockerignore
Adds ignores for
* `node_modules`
* `apps` builds
* `packages` dists
* `fm_*` data dirs
Including these made images unnecessarily large, and could cause `docker build` to fail
> fix: add entries to dockerignore that are unnecessary or harmful to docker build

- .github/workflows/gateway-ui.yml
- .github/workflows/guardian-ui.yml
Fixes #210 
I have updated the `gateway-ui` and the `guardian-ui` images on DockerHub to update their descriptions from their respective READMEs. As there is no way to check GitHub actions locally, it is imperative that these workflow files are cross-verified before merging. 
Also, I'm thinking to add a `workflow-dispatch` option to these workflows. They would allow us to run these publishing to DockerHub actions as and when we want manually. Does this seem like functionality that we would like to have?
> feat: Add updation of dockerhub description from README in workflow [Fixes #210]

- .github/workflows/gateway-ui.yml
- .github/workflows/guardian-ui.yml
Recently #231 was merged to solve issue #210, but the merging of the same is causing the workflows to fail. I think the error is due to the way the relative path to the `README` files is supplied, and I have updated the same in this PR. Hopefully this would fix the failing workflow.
> fix: Change the path for pushing to description to DockerHub

- .github/workflows/gateway-ui.yml
- .github/workflows/guardian-ui.yml
Fixes #235 
As mentioned in this [issue](https://github.com/peter-evans/dockerhub-description/issues/220) here, the `peter-evans/docker-description` requires the content of the repository to be checkout-ed to access the README content. I have added the same in this PR. 
This should hopefully fix the original issue #210!
> Fix: Fix the DockerHub description push workflow [Fixes #235]

- mprocs-nix-gateway.yml
- scripts/mprocs-nix-gateway.sh
- scripts/mprocs-user-shell.sh
When starting up gateway ui in devimint scenarios, we should configure REACT_APP_FM_GATEWAY_API and REACT_APP_FM_GATEWAY_PASSWORD to values set by devimint
> fix: configure gateway ui env from devimint env

- turbo.json
Invalidates turbo cache on `@fedimint/eslint-config` and `@fedimint/tsconfig` dev dependency changes. This fixes a bug where `turbo lint` would require `turbo build` for the latest lint rules to take effect.
ref: https://turbo.build/repo/docs/core-concepts/caching
> fix: don't cache results of lint and test

- apps/gateway-ui/src/App.tsx
- apps/gateway-ui/src/components/WithdrawCard.tsx
- apps/guardian-ui/src/App.tsx
- apps/guardian-ui/src/components/ConnectGuardians.tsx
- apps/guardian-ui/src/components/Login.tsx
- apps/guardian-ui/src/components/RunDKG.tsx
- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/components/VerifyGuardians.tsx
- apps/guardian-ui/src/setup/FederationSetup.tsx
- packages/eslint-config/index.js
- packages/ui/.eslintrc.js
- packages/ui/src/CopyInput.tsx
- packages/ui/src/FormGroup.tsx
- packages/ui/src/RadioButtonGroup.tsx
Fixes #198 
The PR accomplishes the following:
- Remove all the instances of the `HStack` and `VStack` components from the codebase and replace the same with `Flex` with the same gap properties. 
- Add `ESLint` rules to ban these components, and add suggestion messages to use `Flex` instead.
> refactor: Ban HStack and VStack components

- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/components/TermsOfService.tsx
- apps/guardian-ui/src/setup/FederationSetup.tsx
- apps/guardian-ui/src/utils/env.ts
Closes #248
Stringifies & parses env to avoid react-scripts compiler optimizations of environment variables. See comment in `guardian-ui/utils/env.ts` for more information on why this was done and how it works.
This bit of code is just a hack until #224 is implemented, since that wouldn't get any of the compiler optimizations since the config would be loaded dynamically.
> fix(guardian-ui): add getEnv utility for avoiding compiler env var optimizations

- apps/guardian-ui/src/assets/svgs/modules.svg
- apps/guardian-ui/src/assets/svgs/plus.svg
- apps/guardian-ui/src/assets/svgs/trash.svg
- apps/guardian-ui/src/components/ConnectGuardians.tsx
- apps/guardian-ui/src/components/MetaFieldFormControl.tsx
- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/types/api.ts
- apps/guardian-ui/src/utils/validators.ts
- packages/ui/src/FormGroup.tsx
- packages/utils/src/i18n.tsx
Closes #183
* Adds configuration form field to specify fields for `meta`
* Only visible to leader
* By default always shows disabled `federation_name` that matches the federation name field
* Will show meta fields from `FM_EXTRA_DKG_META`, but they will be editable
* Adds list of custom meta during follower confirmation step
* Doesn't show `federation_name` since it's shown separate as `Federation name`
Note that this does **not** add anything to show you your running federation's meta fields, that will be handled by #184.
> feat(guardian-ui): meta fields

- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/languages/es.json
- apps/guardian-ui/src/languages/ko.json
Adds a "Confirm password" field, might also want to put the "click to view password" options.
Had an issue with a federation setup today: 1 guardian forgot their password after clicking away rom the "verification codes" section of federation setup. this meant that the guardian couldn't continue setup and all the other guardians were already in a state waiting for that specific guardian and couldn't do a hard reset, which bricked the entire federation.
@wbobeirne @sethwynne plz fix so it looks nice and fits UI scheme but until fedimint allows for hard reset having this as a backstop will be useful.
> feat: confirm password field

- apps/guardian-ui/src/components/VerifyGuardians.tsx
addresses #254 , if user is in VerifiedConfigs prefills enteredHashes
> feat: prefills hashes if we're already in VerifiedConfigs

- apps/gateway-ui/src/App.tsx
- apps/gateway-ui/src/components/DepositCard.tsx
- apps/gateway-ui/src/components/FederationCard.tsx
- apps/gateway-ui/src/components/InfoCard.tsx
- apps/gateway-ui/src/languages/en.json
- apps/gateway-ui/src/languages/es.json
- apps/gateway-ui/src/languages/ko.json
- apps/gateway-ui/src/types.tsx
When gateway is deployed on mainnet and testnet, gateway address and node links should point to valid mempool.space links.
On signet, we assume gateway is deployed on mutinynet.com where we point both links. When gateway is on regtest, or the network is not yet known, we don't show "view in explorer" links
Changes in gateway UI take effect after https://github.com/fedimint/fedimint/pull/3455 which introduces `network` field to gateway info. To validate these changes before the upstream changes modify the `network` prop in `FederationCard` and  observe how the links are affected. Valid network values are `"main" | "test" | "signet" | "regtest"`
closes #242
> fix: gateway explorer links

- mprocs-nix-gateway.yml
- scripts/mprocs-nix-guardian.sh
Closes #262, closes #261
* Add `set -eo pipefail` to mprocs scripts
* Add `stop: SIGKILL` to mprocs bash scripts
* Add `mprocs-nix-guardian.sh` script for `mprocs-nix-gateway.yml` to run a guardian UI
> Add guardian ui to `nix-gateway`, fix scripts not exiting

- apps/guardian-ui/src/components/GatewaysCard.tsx
- docker-compose.yml
- flake.lock
- flake.nix
Closes #247, allows for #266 to be worked on
* Updates `fedimint` to `23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b` in nix / docker
* Updates the `listGateways` response type to prevent crash
> Update fedimint to `23ee7c`, fix listGateways response

- apps/guardian-ui/src/components/GuardiansCard.tsx
@Kodylow helped me set up the ui repos yesterday and I saw a small error with the status label for the guardian UI.
> fix: status-fix typo

- flake.nix
adds yarn install check when entering `nix develop` and starship to shell, turbo bin gets installed by yarn install instead of nix.
> nix develop shellHook for yarn install and starship

- apps/guardian-ui/src/components/VerifyGuardians.tsx
> fix: text spacing on verify guardians screen

- apps/guardian-ui/package.json
Fixes a regression from #284, the `qrcode.react` module wasn't added to package.json causing docker image builds to fail.
> fix(guardian-ui): add missing qrcode.react package

- apps/guardian-ui/src/components/NumberFormControl.tsx
- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/languages/en.json
Addresses #280 
What should the recommended minimum be here and any recommendations on copy for the warning? Should I have it link to a more in-depth explanation in the fedimint docs?
> Block confs warning

- README.md
remove default application address and passwords from setup docs, to clarify need to fill-in  user specified values
> docs: explicitly encourage replacing app address and passwords

- apps/guardian-ui/src/components/RoleSelector.tsx
- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/languages/es.json
- apps/guardian-ui/src/languages/ko.json
- apps/guardian-ui/src/setup/FederationSetup.tsx
- packages/ui/src/Header.tsx
- packages/ui/src/RadioButtonGroup.tsx
Makes several changes to the Role Selector page:
Old:
New:
1. Updates to copy:
- Change to "Welcome, Guardian" to avoid stacking big "Fedimint" and make it easier to fit title on mobile screen
- Setup Leader: slarifies that it's just for setup, not a difference among guardians
- Follower: Clarifies their role as after setup leader and that that's when the actual federation gets set up.
- Removes mainnet warning: we should do the mainnet warnings on the leader configuration page if they actually select mainnet, not preemptively. Also tells ppl to file issues with us.
2. Moves warning below role selector, above next button:
- On mobile the big warning pushes the follower option below the fold, this looks and makes it more like an "acknowledge by clicking next"
3. Fixes mobile UI layout
- …
> Role selector Mobile Updates

- apps/guardian-ui/src/components/SetupProgress.tsx
Addresses #293 
Removes text for progress bar on mobile so it doesn't overlap. Will eventually change to mobile specific progress bar per figma designs without the radials:
old:
new:
> feat: clean setup bar progress for mobile view

- apps/gateway-ui/src/components/BalanceCard.tsx
- apps/gateway-ui/src/components/DepositCard.tsx
- apps/gateway-ui/src/components/FedNameCard.tsx
- apps/gateway-ui/src/components/FederationCard.tsx
- apps/gateway-ui/src/components/WithdrawCard.tsx
- apps/gateway-ui/src/languages/en.json
- apps/guardian-ui/src/languages/en.json
Made some copy changes per discussions from design call earlier:
1. Change top title to "Lightning Gateway Dashboard" to make it more clear (currently easily confused with guardian dashboard)
2. Move federation name onto balance card
3. Add clarifications to deposit and withdraw for which direction ecash is going, people have found that confusing "So if I deposit bitcoin then that means I get ecash?", it's unintuitive.
> fix: lightning gateway dashboard changes

- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/languages/es.json
- apps/guardian-ui/src/languages/ko.json
Leader and Follower already answer "Are you creating a Federation or joining one?", also "joining" is unclear given distinction between guardian and client.
> Remove redundant copy

- apps/guardian-ui/src/components/VerifyGuardians.tsx
- apps/guardian-ui/src/setup/SetupContext.tsx
- apps/guardian-ui/src/types/setup.ts
- apps/guardian-ui/src/utils/validators.ts
- docker-compose.yml
- flake.lock
- flake.nix
At the config verification step after all the guardians have verified other configs, if the leader continued their own setup to completion before the follower guardians, there is a chance the followers would not be able to **resume and complete** their setup since we relied on their servers being able to continuously poll the leader's server for consensus configuration.
This PR fixes the bug, allowing all guardians to complete federation set-up in any order, provided they have successfully coordinated through config verification.
1. Before fix:
- Follow federation set-up through config verification until you see "All guardians have verified their codes"
- Reload any guardians setup page to confirm that the verified codes are automatically pre-filled on reload
- Complete set-up for the …
> guardian-ui: fix config verification

- apps/guardian-ui/src/assets/svgs/lightbulb.svg
- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/components/VerifyGuardians.tsx
- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/languages/es.json
- apps/guardian-ui/src/languages/ko.json
- apps/guardian-ui/src/setup/FederationSetup.tsx
- packages/ui/src/FormGroup.tsx
- packages/ui/src/FormGroupHeading.tsx
- packages/ui/src/RadioButtonGroup.tsx
Fixes mobile UI for set configurations leader setup per new figma specification on desktop and mobile:
Doesn't fix header spacing of Left of dashboard / role selector but middle on intermediate setup, will have to handle in a separate PR because Header doesn't inherit what setup progression step the user is in.
New:
> Leader mobile UI SetConfigurations

- apps/guardian-ui/src/assets/svgs/check-circle.svg
- apps/guardian-ui/src/assets/svgs/x-circle.svg
- apps/guardian-ui/src/components/VerifyGuardians.tsx
- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/setup/FederationSetup.tsx
- packages/ui/src/FormGroup.tsx
Updates Verify Configs page for mobile UI:
> Verify configs mobile UI

- README.md
- docker-compose.yml
- package.json
add more doc cleanups
- reword paragraphs in "Running a Release" to clarify intent and instructions
- dev section, list "Running with mprocs" as option 2 before the more involved "Running with Docker Compose and Yarn manually", now at option 3
- update details in "Running with Docker Compose and Yarn manually"
- remove unused `yarn dev` script
- aligns docker compose volume setup, then simplify teardown
> doc cleanups

- apps/guardian-ui/src/assets/svgs/solo.svg
- apps/guardian-ui/src/components/ConnectGuardians.tsx
- apps/guardian-ui/src/components/RoleSelector.tsx
- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/setup/FederationSetup.tsx
- apps/guardian-ui/src/types.tsx
Adds solo guardian changes from pair programming with justin and will
> feat: solo-guardians

- apps/guardian-ui/src/components/SetConfiguration.tsx
in case they go back and forth on the role selector.
> fix: overwrite numPeers to 1 for solo

- apps/guardian-ui/src/components/GuardiansCard.tsx
Nulls guardian card for solo guardian dashboard.
> feat: no guardians card for solo

- apps/gateway-ui/src/GatewayApi.ts
Closes #338. Replaces both instances of a string response with `res.json()`, not just for objects after all!
> fix: decode string responses as json for address and deposit txid

- README.md
- docker-compose.yml
- flake.lock
- flake.nix
Replaces #334, sticking with commit hash and updating to rc5 (I think that PR was still rc4?)
> chore: bump fedimint to 0.2.0-rc5

- apps/guardian-ui/src/components/MetaFieldFormControl.tsx
fixes #344 
Having the box for the Derived ones makes the spacing look nicer, tried both ways and when you don't leave the spacing then the center gap looks weird.
> fix: trashcan icon for custom meta fields

- README.md
- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/components/VerifyGuardians.tsx
- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/languages/es.json
- apps/guardian-ui/src/languages/ko.json
- apps/guardian-ui/src/setup/FederationSetup.tsx
- flake.lock
- flake.nix
- packages/types/src/federation.ts
Add UX for restarting federation setup. These need design review as the UX spec doesn't include restart experience
**Validations**
close #253
> Restart federation setup

- apps/gateway-ui/src/GatewayApi.ts
- apps/gateway-ui/src/assets/svgs/x-circle.svg
- apps/gateway-ui/src/components/BalanceCard.tsx
- apps/gateway-ui/src/components/FedNameCard.tsx
- apps/gateway-ui/src/components/FederationCard.tsx
- apps/gateway-ui/src/languages/en.json
- apps/gateway-ui/src/languages/es.json
- apps/gateway-ui/src/languages/ko.json
Needs design input and I think we should use toasts for errors we've got that whole section in the top right that's blank rn.
Need design input on how to view multiple federations too, think we're at the point we can start implementing that
> feat: Leave Federation

- apps/guardian-ui/src/components/VerifyGuardians.tsx
fixes a state bug where `toggleConsensusPolling(false) would mean `VerifyGuardians` page doesn't activate next button even after all guardians have been verified. before this fix, the user is forced to reload page to proceed
> fix: update local state for verify config hashes

- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/components/GatewaysCard.tsx
- apps/guardian-ui/src/types.tsx
makes guardian api type declaration and implementation simpler 🖌️ 
closes #176
> refactor: simplify guardian api implementation

- apps/guardian-ui/src/components/SetConfiguration.tsx
we should default these open, based on feedback from federation setups defaulting closed was a mistake.
> fix: default open

- apps/gateway-ui/src/GatewayApi.ts
If you set the Gateway API in the server side environment variables it'll set it as authed for any client logging in. Removes pull from env for gateway api test password.
> Fix gateway api auth

- packages/utils/src/i18n.tsx
Resolves #350 
This PR allows i18next to detect the language set in the user's browser and translate the page.
Translation happens seamlessly now.
> feat: allow browser language detection

- package.json
- yarn.lock
Closes #370.
Ran `npx @turbo/codemod update` to do the update as recommended by turbo. Should hopefully alleviate "too many open files" issues with the latest version, but we might also want to check on react-scripts dependencies (e.g. webpack) if there have been any updates to those that might be responsible.
> chore: update turbo

- apps/guardian-ui/src/components/SetConfiguration.tsx
fixes: https://github.com/fedimint/ui/issues/379
> fix: finality_delay = block_confs - 1

- apps/guardian-ui/src/components/RoleSelector.tsx
Lets you pass in `role` as a query param so we can skip the first setup page, we've found it a hiccup when doing setups for fedi
> feat: pass in query param for role

- flake.lock
- flake.nix
Bumps fedimint version in nix flake to commit including meta module so I can start on the guardian UI for meta updates
> chore: bump fedimint to meta module

- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/setup/SetupContext.tsx
fixes https://github.com/fedimint/ui/issues/385
We weren't properly loading the state from localStorage, and we were setting numPeers from connected Peers not from stateNumPeers. This lets the setup leader refresh and maintain state and connections to peers, and doesn't kick to DKG immediately on refresh.
> fix: set numPeers correctly

- .dockerignore
- .gitignore
- README.md
- scripts/mprocs-nix.sh
https://github.com/fedimint/fedimint/pull/4470 moved dev shell outputs to `./target-nix`. This PR updates the UI docs for the same
> chore: reference target-nix when using local FM

- packages/types/src/federation.ts
Removes old fields that are no-longer present in type returned by FM API
closes #390
> chore: update ClientConfig type

- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/types.tsx
adds `GuardianApi` method for fetching federation id. Enabled by https://github.com/fedimint/fedimint/pull/4576
> feat: api for fetching federation id

- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/setup/SetupContext.tsx
- apps/guardian-ui/src/utils/api.ts
- packages/types/src/modules.ts
Fixes https://github.com/fedimint/ui/issues/397
Consensus and Local are now required for submitting module params in setup so we don't filter them out anymore for the follower, plus me and eric ran into a runtime issue where the password was nulled on refresh that this fixes by doing a !!password check
> fix: required config gen local and consensus + fix password runtime error

- apps/guardian-ui/src/languages/en.json
- apps/guardian-ui/src/setup/SetupContext.tsx
This just sets a random guardian name for the user instead of letting them pick one. 
Until we have something like a nostr login where you can testify to being a guardian the names here are useless and cause a bunch of headaches during setup if users don't want to correlate that they're also guardians.
> Random Guardian Names

- apps/guardian-ui/src/components/ConnectGuardians.tsx
- apps/guardian-ui/src/languages/en.json
Changes the placeholder to clarify that you're waiting for them, had some feedback that it looked like Guardian 2 etc were already supposed to be connected by naming them that
> feat: waiting on guardians instead of placeholders

- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/languages/en.json
Addresses #393 
This logic generates a 16-character password that guardians can copy and backup and present during password check.
Question: At what point should password check happen? 
**Updated user flow**:
[Screencast from 02-04-2024 10:41:39 ASUBUHI.webm](https://github.com/fedimint/ui/assets/41724425/143120c3-2d68-40e1-a727-c5b1f90e321b)
> feat: define logic to autogenerate guardian password

- README.md
The setup instructions for running fedmint UI in development mode using mprocs do not include the instruction to run 'yarn install'
The readme was updated to to include that step
> chore: update Readme instructions for mprocs setup

- Dockerfile.guardian-ui
- README.md
- apps/guardian-ui/public/config.json.example
- apps/guardian-ui/src/GuardianApi.ts
- apps/guardian-ui/src/components/TermsOfService.tsx
- apps/guardian-ui/src/setup/FederationSetup.tsx
- apps/guardian-ui/src/setup/SetupContext.tsx
- apps/guardian-ui/src/setupProxy.js
- apps/guardian-ui/src/types.tsx
- apps/guardian-ui/src/utils/env.ts
- scripts/write-config-from-env.js
closes remaining todos on #369 namely:
[ ] - EnvVars type defined in two spots
[ ] - move config state into it's own context
merge conflicts were encountered when comparing changes and fixed locally.
@Kodylow please take a look and see if I'm on track
> Config json reboot cleanup

- apps/guardian-ui/src/languages/en.json
fixes #417 
@Kodylow I noticed this text doesn't exist in spanish translations file. Is this intentional or someone hasn't gotten to that yet?
> chore: update authenticate as guardian btn text

- apps/gateway-ui/src/components/FederationCard.tsx
- packages/ui/src/Login.tsx
Closes #419 
[Visibility toggle.webm](https://github.com/fedimint/ui/assets/41724425/ed36e0af-e644-4c5e-a7a9-ac5f597eb9d7)
Using eye Icon instead of text:
[visibility eye icon.webm](https://github.com/fedimint/ui/assets/41724425/1ba8b169-ce3f-42ce-8ef3-e47ee5582312)
> feat: add password visibility toggle

- apps/gateway-ui/src/languages/en.json
- apps/guardian-ui/src/components/SetConfiguration.tsx
- apps/guardian-ui/src/languages/en.json
made a couple minor changes:
- Forces you to start by generating a password, lets you edit it but improves likelihood they use the secure password
- Only generates once to clarify, found it confusing you could keep clicking it
- Moved acknowledgement checkmark for admin password to right above Next, was confusing having it super high up and can't see it when you scroll to bottom and the next is disabled
> fix: generate password fixes

- apps/router/src/guardian-ui/components/setup/screens/setConfiguration/ConfirmPasswordModal.tsx
- apps/router/src/guardian-ui/components/setup/screens/verifyGuardians/VerifyGuardians.tsx
- apps/router/src/hooks/custom/useTrimmedInput.tsx
- apps/router/src/hooks/index.tsx
Issue #573 
**Objective:** Improve input handling by trimming unnecessary whitespace from passwords and guardian names during confirmation, enhancing user experience and reducing errors.
---
- **Hooks in `useTrimmedInput.tsx`:** The `useTrimmedInput` hook was reused and adapted to handle password inputs, ensuring that whitespace is trimmed automatically to reduce validation errors.
---
- **Automatic Whitespace Removal:** Trims leading and trailing spaces during input to avoid validation errors.
- **Error Reduction:** Prevents issues caused by unintentional whitespace in passwords or guardian names.
- **Consistency:** Ensures uniform input sanitization across the application.
---
- **Before:** Manual input management (`useState`) lacked automatic trimming.
- **Now:** `useTrimmedInput` …
> Trim passwords input

- .github/workflows/fedimint-ui-docker.yml
Our dockerhub is far too noisy. [see here](https://hub.docker.com/r/fedimintui/fedimint-ui/tags)
Let's only upload tagged commits/releases to dockerhub. 
cc @tsmith123
> feat: disable DockerHub upload except for tags

- apps/router/src/hooks/custom/useQuery.tsx
- apps/router/src/hooks/index.tsx
- apps/router/src/pages/Home/Home.test.tsx
- apps/router/src/pages/Home/Home.tsx
Fixes #579 
This PR allows a user to pass a `url` query string param for a guardian/gateway when loading the UI. This string value will be added to the input box automatically.
**Note:** whilst we could connect automatically this would potentially cause a few issues such as if a user clicked back in the browser after connecting it would then connect them again. I prefer asking the user to click the connect button because this means they will follow the same flow as those who don't provide a query string param meaning we can reuse the same logic.
**Example**
```
https://fedimint-ui.com/?url=wss://btcpp-11.cypheru.net/ws/
```
> Pass url as query string param

- apps/router/src/pages/Home/Home.test.tsx
- apps/router/src/pages/Home/Home.tsx
After some feedback in #628 this PR adds an example url as the placeholder on the Homepage to indicate it's a websocket url that's required.
> Improve Placeholder On Homepage

- apps/router/src/guardian-ui/admin/FederationAdmin.tsx
- apps/router/src/guardian-ui/components/dashboard/admin/InviteCode.tsx
The layout of the Guardian admin page quickly degrades when the viewport is narrowed. This PR is the first in a series of UI updates to improve the responsiveness.
**Old Mobile View**
**New Mobile View**
**Old Desktop View**
**New Desktop View**
> Improve Guardian Responsiveness

- apps/router/src/guardian-ui/components/dashboard/tabs/meta/manager/CustomMetaFields.tsx
- apps/router/src/guardian-ui/components/dashboard/tabs/meta/manager/IconPreview.tsx
- apps/router/src/guardian-ui/components/dashboard/tabs/meta/manager/SitesInput.tsx
- apps/router/src/guardian-ui/utils/debounce.ts
Closes #605 
Adds privacy feature to control when image URLs are validated and previewed in the custom metadata fields and sites input components. It adds a toggle switch that allows users to disable automatic external requests for image validation when privacy is a concern.
[Screencast from 2025-03-09 01-54-58.webm](https://github.com/user-attachments/assets/3283cd5a-dcca-46b7-92af-7a56366f3a27)
> Feat: Add toggle for privacy check for ValidateIcon 

- apps/router/src/api/GuardianApi.ts
- packages/types/src/bitcoin.ts
Fedimint version 0.6 returns a different response shape from the `check_bitcoin_status` endpoint and this makes it impossible to start the guardian ceremony. This PR handles responses from versions 0.5 and 0.6.
> Handle New Bitcoin Status Response

- apps/router/src/App.tsx
Fixes #629 
This PR ensures that a `service` exists in local storage when the app loads. If it doesn't then the user is redirected to the home page so that `service` can be set before continuing.
> fix: check for service in storage

- README.md
- docs/nix.md
* I noticed some contributors are having trouble setting up the dev environment, as they don't have access to fedimint infrastructure and/or they're using WSL. The nix environment seems like the best option for them.
* The PR re-adds the nix setup instructions to the project.
> chore: add nix docs

- README.md
- apps/router/src/constants/index.tsx
- flake.nix
Bump version to 0.6.3 for unique tags
> chore: bump version to 0.6.3
