apps/guardian-ui/src/GuardianApi.ts, apps/guardian-ui/src/components/FederationDashboard.tsx
Show connection info for the federation
**Before**
**After**
=> feat(fed): show federation connection info

apps/guardian-ui/src/GuardianApi.ts
=> refactor: add type safety to rpc methods

apps/guardian-ui/src/admin/FederationAdmin.tsx, apps/guardian-ui/src/components/AdminHeader.tsx
This pr introduces the updated design for the FederationAdmin Header
[Link to Figma design](https://www.figma.com/file/ioeAVbWBc3ow2RaZETatM7/Fedimint?node-id=854%3A21343&mode=dev)
=> update: Admin Header

apps/guardian-ui/src/GuardianApi.ts
=> fix: gracefully teardown/setup setup/consensus API

apps/gateway-ui/src/App.tsx, apps/gateway-ui/src/components/FederationCard.tsx, apps/gateway-ui/src/types.tsx, apps/guardian-ui/src/GuardianApi.ts, apps/guardian-ui/src/components/ConnectedNodes.tsx, apps/guardian-ui/src/types.tsx
- Update gateway types after https://github.com/fedimint/fedimint/pull/2758 and https://github.com/fedimint/fedimint/pull/2778
- Add types for route hints: Closes #80
=> Type Updates

apps/guardian-ui/src/admin/FederationAdmin.tsx, apps/guardian-ui/src/types.tsx
=> fix: status response type definition

mprocs-nix-gateway.yml, mprocs-nix-guardian.yml, mprocs.yml, turbo.json
build `@fedimint/utils` before apps and build apps in mprocs shells
fixes #109
=> fix: build @fedimint/utils before apps

apps/guardian-ui/src/components/AdminHeader.tsx
Checks consensus numbers for offline peers, surfacing it to the user/Guardian.
Run `mprocs -c mprocs.yml`
Get to dashboard. Observe 2/2.
Run in a shell `docker stop ui-fedimintd_2-1`
Wait, refresh localhost:3000, and observe 1/2
Colors coming soon.
Work toward: https://github.com/fedimint/ui/issues/94
=> feat: dashboard accurately display on/offline peers

.gitignore, README.md, docker-compose.yml, mprocs.yml
I used four fedimints since I imagine this being the "standard". We can now also dev on UI/UX for when consensus concerns arise by turning off a fedimint or two.
Marking Draft because I haven't actually tested a setup with this, but wanted to get it out there.
=> build: four fedimintds for dev env

turbo.json
=> fix: disable turbo cache for guardian-ui and gateway-ui dev commands

apps/guardian-ui/src/admin/FederationAdmin.tsx, apps/guardian-ui/src/languages/en.json, apps/guardian-ui/src/types.tsx
Displays Peer Id and Name alongside connection status.
Fixes typo in API endpoint field name.
=> 94 guardian show list of guardians in federation

apps/gateway-ui/src/GatewayApi.ts
=> fix(gateway-ui): update connect param to invite_code

apps/guardian-ui/src/GuardianApi.ts, apps/guardian-ui/src/admin/FederationAdmin.tsx, apps/guardian-ui/src/components/BalanceCard.tsx, apps/guardian-ui/src/types.tsx, docker-compose.yml, packages/utils/src/format.tsx, packages/utils/src/index.tsx, packages/utils/src/types.ts
This is identical to PR #170 but targeted against master
=> Merge #170 into `master`

.github/workflows/gateway-ui.yml, .github/workflows/guardian-ui.yml
I tried to make a v0.1.0 tag but it didn't push the image to dockerhub, this should fix that.
=> ci: push image on tag starting with `v`

.github/workflows/gateway-ui.yml, .github/workflows/guardian-ui.yml
I blew it on #208, this should do it
=> ci: fix tag ref check

JUSTFILE
add in some short cuts for guardian and gateway running with nix.
=> chore: improve justfile

apps/guardian-ui/src/components/SetConfiguration.tsx
Hopefully closes https://github.com/fedimint/ui/issues/237
=> fix: use default meta params

apps/gateway-ui/README.md, docker-compose.yml, mprocs.yml
Fixes typo to match rtl password from fedimint docker compose setups and docs.
=> fix: typo thereisnosecondbest

apps/gateway-ui/src/components/WithdrawCard.tsx
basic bitcoin uri handling, can make more robust and check network other address features once we merge network awareness (tb1 vs bc1 etc).
Fixes #271
=> fix: handle bitcoin uri

apps/gateway-ui/src/App.tsx, apps/guardian-ui/src/admin/FederationAdmin.tsx, apps/guardian-ui/src/components/BalanceCard.tsx, apps/guardian-ui/src/components/FederationInfoCard.tsx
=> feat: gateway and guardian dashboard polling

apps/guardian-ui/src/admin/FederationAdmin.tsx, apps/guardian-ui/src/components/ConnectGuardians.tsx, apps/guardian-ui/src/components/InviteCode.tsx, apps/guardian-ui/src/components/VerifyGuardians.tsx, packages/ui/src/CopyInput.tsx, packages/ui/src/Footer.tsx
=> feat: blue bg on invite code with white input fields

README.md, apps/guardian-ui/src/GuardianApi.ts, apps/guardian-ui/src/admin/FederationAdmin.tsx, apps/guardian-ui/src/components/BalanceCard.tsx, apps/guardian-ui/src/components/BitcoinNodeCard.tsx, apps/guardian-ui/src/components/FederationInfoCard.tsx, apps/guardian-ui/src/components/GatewaysCard.tsx, apps/guardian-ui/src/components/GuardiansCard.tsx, docker-compose.yml, flake.lock, flake.nix, packages/types/src/federation.ts, packages/types/src/modules.ts
Closes https://github.com/fedimint/ui/issues/316
=> feat: support fedimint-0.2

.github/templates/failed-backport-issue.md, apps/guardian-ui/README.md, apps/guardian-ui/src/languages/en.json, apps/guardian-ui/src/languages/es.json, apps/guardian-ui/src/languages/ko.json
Block Count is confusing, Should be "Consensus Block Height"
=> fix: blockcount bug + yarn format

apps/gateway-ui/src/GatewayApi.ts, apps/gateway-ui/src/components/WithdrawCard.tsx, apps/gateway-ui/src/languages/en.json, apps/gateway-ui/src/languages/es.json, apps/gateway-ui/src/languages/ko.json
Adds withdraw all fixes from pairing with justin, requires fixes to fedimint.
=> feat: fix withdraw all

apps/guardian-ui/src/components/SetConfiguration.tsx
=> fix: show confirmation settings host

apps/gateway-ui/src/languages/es.json, apps/gateway-ui/src/languages/ko.json, apps/guardian-ui/src/languages/es.json, apps/guardian-ui/src/languages/ko.json, package.json, scripts/translate.js, yarn.lock
adds a translation script, completes all missing translations in en and ko.
=> feat: translation script

apps/gateway-ui/src/components/FederationCard.tsx
=> chore: remove unused imports and vars

flake.nix
should use fedimint not dpc fork
=> Fix: flake.nix

apps/guardian-ui/src/GuardianApi.ts, apps/guardian-ui/src/admin/FederationAdmin.tsx, apps/guardian-ui/src/components/ConfigViewer.tsx, apps/guardian-ui/src/components/DownloadBackup.tsx, apps/guardian-ui/src/languages/en.json, apps/guardian-ui/src/types.tsx, apps/guardian-ui/src/utils/api.ts, flake.lock, flake.nix, packages/types/src/federation.ts
Bumps flake to most recent fedimint master commit to get the download guardian config endpoint and adds flow to download backup: button next to Federation Config + modal to acknowledge they're downloading private key material
=> feat: download guardian backup

README.md, flake.lock, flake.nix
Fixes #392 and also adds bump for FM [v0.3.0-rc.0](https://github.com/fedimint/fedimint/tree/v0.3.0-rc.0)  and v0.3.0-rc.1](https://github.com/fedimint/fedimint/tree/v0.3.0-rc.1)
=> Bump Fedimint

apps/gateway-ui/src/components/BalanceCard.tsx, apps/gateway-ui/src/components/FederationCard.tsx, packages/types/src/gateway.ts
=> feat: show federation name in gateway ui

README.md, flake.lock, flake.nix
- commit # c32bbe8ed8d95ae420b5879e92dda6ce48f5c914
=> chore: bump fm to v0.3.0-rc.3

Dockerfile.guardian-ui, README.md, apps/guardian-ui/public/config.json.example, apps/guardian-ui/src/GuardianApi.ts, apps/guardian-ui/src/components/TermsOfService.tsx, apps/guardian-ui/src/setup/FederationSetup.tsx, apps/guardian-ui/src/setupProxy.js, apps/guardian-ui/src/utils/env.ts, mprocs.yml, scripts/write-config-from-env.js
Closes #224 
I am having trouble with my dev env so would appreciate a solid testing of this. It worked for me one time when things were cooperative.
=> Config json reboot

flake.nix
Still need to test if config.json works.
=> feat: build guardian-ui as nix package

apps/router/src/gateway-ui/components/walletCard/LightningCard.tsx, apps/router/src/gateway-ui/components/walletCard/OnchainCard.tsx, apps/router/src/home/NoConnectedServices.tsx, apps/router/src/languages/en.json
Adds missing locales to the Gateway UI
=> feat: adds missing localizations to gateway ui

packages/ui/src/Login.tsx
This PR reverts the changes made to prevent Gateway login as it also affects Guardian logins too.
=> Revert Login Changes

apps/router/src/languages/ca.json, apps/router/src/languages/de.json, apps/router/src/languages/es.json, apps/router/src/languages/fr.json, apps/router/src/languages/hu.json, apps/router/src/languages/it.json, apps/router/src/languages/ja.json, apps/router/src/languages/ko.json, apps/router/src/languages/pt.json, apps/router/src/languages/ru.json, apps/router/src/languages/zh.json
=> chore: translate

apps/router/src/constants/index.tsx, flake.lock, flake.nix
=> chore: bump fedimint to v0.6.2

Dockerfile, flake.nix
Debugs docker file. re-tags release.
=> chore: debug docker file
